# Generated by Django 3.0.7 on 2020-06-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200624_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='order_list',
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(to='store.Order_Items'),
        ),
    ]
