# Generated by Django 3.0.7 on 2020-06-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200624_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Items',
            new_name='Order_Item',
        ),
    ]
